### ISSUE TITLE
Is this the new place to get recent FakeSMC versions?

### ISSUE THREAD

**Issue by Appyx** [CloverHackyColor/FakeSMC3_with_plugins#1]
Is this version newer than the RehabMan builds on Bitbucket and will it be maintained?

Which plugins replace the following plugins:

* FakeSMC_ACPISensors.kext 
* FakeSMC_CPUSensors.kext
* FakeSMC_GPUSensors.kext
* FakeSMC_LPCSensors.kext
* FakeSMC_SMMSensors.kext

**Comment by SergeySlice** [comment]
I have no relation to RehabMans fork.
My HWSensors is newer.

**Comment by SergeySlice** [comment]
FakeSMC_ACPISensors -> ACPIMonitor
FakeSMC_CPUSensors -> IntelCPUmonitor or AMDCPUMonitor
FakeSMC_GPUSensors -> Geforce, NVClockX, Radeon, or even X3100
FakeSMC_LPCSensors -> F718x, ITEIT87x, W836x
FakeSMC_SMMSensors -> SMIMonitor
ACPIBattery -> VoodooBatterySMC
