### ISSUE TITLE
Clover efi folder -  fan speed not working

### ISSUE THREAD

**Issue by aufuk1** [CloverHackyColor/FakeSMC3_with_plugins#18]
Elitebook 840 G4, clover efi folder. Fan speed not working.
What would you suggest I do?

**Comment by aufuk1** [comment]
Problem solved :)
I was able to read the fan speeds instantly.

![image jpeg cc2682b1c2f1d04ede0bab0d06938ba2](https://user-images.githubusercontent.com/13665547/183284936-3f35d204-1ec0-436e-be5f-4388e87ae3fc.jpeg)

[SSDT-FAN.aml.zip](https://github.com/CloverHackyColor/FakeSMC3_with_plugins/files/9276545/SSDT-FAN.aml.zip)

**Comment by SergeySlice** [comment]
This is wrong HWMonitor, not compatible with these plugins.
