### ISSUE TITLE
VoodooBatterySMC : Battery indicator not working

### ISSUE THREAD

**Issue by aufuk1** [CloverHackyColor/FakeSMC3_with_plugins#19]
I am using Fakesmc3 (Monterey 12.5) with OC 0.8.3, everything works fine but only the battery indicator is not working. What would you suggest I do?
Used kexts:
FakeSMC.kext
ACPIMonitor.kext
IntelMCHMonitor.kext
VoodooBatterySMC.kext

Elitebook 840 G4 laptop

Thank you

**Comment by aufuk1** [comment]
Solved :)

[SSDT-BAT0.aml.zip](https://github.com/CloverHackyColor/FakeSMC3_with_plugins/files/9279042/SSDT-BAT0.aml.zip)

and

ECEnabler.kext

**Comment by SergeySlice** [comment]
Good to see your success.
