### ISSUE TITLE
HW

### ISSUE THREAD

**Issue by iam-k0kos** [CloverHackyColor/FakeSMC3_with_plugins#3]
Привет. Я использую MacOS High Sierra на AMD 3600x вместе с GTX 1070. Скачал release 240, переместил оттуда приложение HWMonitorSMC2 в Программы, из release 241 переместил ACPIMonitor, AmdCPUMonitor, FakeSMC, GeForceSensor, ITEIT87x (мат плата Asus X470 i gaming, установлен IT8665E) в efi/clover/kext/other. Не показывает вообще информацию о вентиляторах и процессоре, показывает температуру и состояние накопителей, и температуру и нагрузку gtx 1070. В чем может быть проблема?

**Comment by SergeySlice** [comment]
Вероятно в этих плагинах нет поддержки конкретно этих вариантов чипов.
Чип 8665 поддерживается, значит нужно смотреть, правильно ли все установлено.
