### ISSUE TITLE
Relevance in clover last version and MacOS Catalina

### ISSUE THREAD

**Issue by merelyigor** [CloverHackyColor/FakeSMC3_with_plugins#5]
Подскажи актуально ли использовать твои плагина на каталине и последнем кловере если я использую VirtualSMC.kext ?
у меня процессор intel core и видео rx580

**Comment by SergeySlice** [comment]
Нет, они несовместимы с VirtualSMC. Плагины пишутся под конкретную версию SMC драйвера, в данном случае это FakeSMC 3.x
С Каталиной и последним Кловером проблем нет.
Процессор и видео поддерживаются.
