### ISSUE TITLE
GeforceSensor.kext

### ISSUE THREAD

**Issue by chris1111** [CloverHackyColor/FakeSMC3_with_plugins#7]
Please add support for **GeForce 630** this card is native on macOS and the the Geforce sensors Kozlek works but I want using your FakeSMC but no Fan is indicate in the HWMonitorSensor.app
Thanks

**Comment by SergeySlice** [comment]
Kepler and Femi cards are fully supported by this project including temperatures, fans and frequencies.

**Comment by chris1111** [comment]
> Kepler and Femi cards are fully supported by this project including temperatures, fans and frequencies.

The fan is not show in the app see picture and my setup is correct

![Capture d’écran, le 2020-07-05 à 10 06 29](https://user-images.githubusercontent.com/6248794/86534585-6b770700-bea7-11ea-9624-f1d6af99517e.png)

**Comment by chris1111** [comment]
Anyway issue closed I change for a Geforce GT 710
