### ISSUE TITLE
Small Cosmetic issue

### ISSUE THREAD

**Issue by ghost** [CloverHackyColor/FakeSMC3_with_plugins#9]
CPU Temperature named as Ambient added screenshot. Radeon Monitor Works well Thank you for updating kexts.
![Ekran Resmi 2021-02-15 01 57 22](https://user-images.githubusercontent.com/70968210/107891716-71e75a00-6f31-11eb-89b6-06b1fcb08a6b.png)
Specs Ryzen 3500x Gigabyte B450M H (SMC Chip ITE) Radeon Rx 5600XT

**Comment by SergeySlice** [comment]
Thanks for the testing. What kexts and plugins installed?

**Comment by TurannUl** [comment]
![Ekran Resmi 2021-02-19 05 02 05](https://user-images.githubusercontent.com/70968210/108446712-9e6fde80-726f-11eb-8eb5-586138c03924.png)

**Comment by ghost** [comment]
amdcpumonitor,fakesmc,ITEIT87x,RadeonMonitor.

**Comment by ghost** [comment]
issue not solved with v243 still exits UP!
![Ekran Resmi 2021-02-26 01 44 31](https://user-images.githubusercontent.com/70968210/109229398-4a677b80-77d4-11eb-8e98-cac119cc536a.png)

**Comment by ghost** [comment]
UP!
